service:
  name: yigim-server

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  environment:
    STAGE: ${self:custom.stage}
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
        - dynamodb:GetItem
        - dynamodb:CreateItem
        - dynamodb:UpdateItem
      Resource:
        - Fn::Join:
            - ':'
            - - arn:aws:lambda
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - function:*
custom:
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  webpack:
    keepOutputDirectory: true
    includeModules: true
    packager: yarn
  serverless-offline:
    httpPort: 9000
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
functions:
  #  --- http ---
  testsCreate:
    handler: src/http/testsCreate.handler
    events:
      - http:
          method: post
          cors: true
          path: tests
  testsReadItem:
    handler: src/http/testsReadItem.handler
    events:
      - http:
          method: get
          cors: true
          path: tests/{testId}
  resultsCreate:
    handler: src/http/resultsCreate.handler
    events:
      - http:
          method: post
          cors: true
          path: tests/{testId}/results
  resultsReadList:
    handler: src/http/resultsReadList.handler
    events:
      - http:
          method: get
          cors: true
          path: tests/{testId}/results
resources:
  Resources:
    TestTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: 'test'
    ResultTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: testId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: testId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: 'result'
